ARG CUDA_VERSION=13.0.2
FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04

LABEL org.opencontainers.image.source=https://github.com/z-lab/paroquant
LABEL org.opencontainers.image.description="Container for vLLM inference"
LABEL org.opencontainers.image.licenses=MIT

ARG PYTHON_VERSION=3.12

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    build-essential \
    git \
    curl \
    ca-certificates \
    libibverbs-dev \
    libnuma-dev \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    python${PYTHON_VERSION} \
    python${PYTHON_VERSION}-dev \
    python${PYTHON_VERSION}-venv \
    python3-pip \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 \
    && update-alternatives --set python3 /usr/bin/python${PYTHON_VERSION} \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ENV TORCH_CUDA_ARCH_LIST="8.0 8.6 8.7 8.9 9.0 10.0 12.0 12.1"

RUN pip install vllm==0.15.1 accelerate --no-cache-dir --extra-index-url https://wheels.vllm.ai/0.15.1/cu130 --extra-index-url https://download.pytorch.org/whl/cu130

COPY ./kernels ./kernels
RUN pip install ./kernels --no-cache-dir --no-build-isolation

COPY . .

ENV TRITON_PTXAS_PATH=/usr/local/cuda/bin/ptxas
ENTRYPOINT ["python", "scripts/interactive_gen.py"]