from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


def _run(cmd: list[str], cwd: Path | None = None) -> None:
    proc = subprocess.run(cmd, cwd=str(cwd) if cwd else None, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"Command failed ({proc.returncode}): {' '.join(cmd)}")


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _hash_tree(path: Path) -> dict[str, str]:
    if path.is_file():
        return {path.name: _sha256_file(path)}

    out: dict[str, str] = {}
    for file in sorted(p for p in path.rglob("*") if p.is_file()):
        out[str(file.relative_to(path))] = _sha256_file(file)
    return out


def build_mlx(hf_dir: Path, mlx_dir: Path, q_bits: int, q_group_size: int) -> Path:
    """Build an MLX artifact from HF-compatible export."""
    if mlx_dir.exists():
        # mlx_lm.convert expects destination path to not exist.
        shutil.rmtree(mlx_dir)

    cmd = [
        sys.executable,
        "-m",
        "mlx_lm.convert",
        "--hf-path",
        str(hf_dir),
        "--mlx-path",
        str(mlx_dir),
        "-q",
        "--q-bits",
        str(q_bits),
        "--q-group-size",
        str(q_group_size),
    ]
    _run(cmd)
    return mlx_dir


def _find_llama_quantize(llama_cpp_dir: Path) -> Path:
    candidates = [
        llama_cpp_dir / "build/bin/llama-quantize",
        llama_cpp_dir / "llama-quantize",
        llama_cpp_dir / "quantize",
    ]
    for cand in candidates:
        if cand.exists() and cand.is_file():
            return cand

    global_cmd = shutil.which("llama-quantize")
    if global_cmd:
        return Path(global_cmd)

    raise FileNotFoundError(
        "Could not find llama-quantize binary. Build llama.cpp first (e.g. cmake --build build -j)."
    )


def build_gguf(hf_dir: Path, gguf_dir: Path, llama_cpp_dir: Path, quants: tuple[str, ...]) -> dict[str, Path]:
    """Build GGUF artifacts (f16 + requested quant levels)."""
    convert_script = llama_cpp_dir / "convert_hf_to_gguf.py"
    if not convert_script.exists():
        raise FileNotFoundError(f"convert_hf_to_gguf.py not found in {llama_cpp_dir}")

    gguf_dir.mkdir(parents=True, exist_ok=True)

    fp16 = gguf_dir / "model-f16.gguf"
    _run([sys.executable, str(convert_script), str(hf_dir), "--outfile", str(fp16), "--outtype", "f16"])

    quantizer = _find_llama_quantize(llama_cpp_dir)
    outputs = {"f16": fp16}

    for quant in quants:
        out = gguf_dir / f"model-{quant}.gguf"
        _run([str(quantizer), str(fp16), str(out), quant])
        outputs[quant] = out

    return outputs


def build_ollama(ollama_dir: Path, gguf_outputs: dict[str, Path], default_quant: str) -> Path:
    """Generate Ollama Modelfile referencing exported GGUF."""
    if default_quant not in gguf_outputs:
        raise KeyError(f"Requested default quant {default_quant} missing from GGUF outputs")

    ollama_dir.mkdir(parents=True, exist_ok=True)
    rel_path = Path("..") / "gguf" / gguf_outputs[default_quant].name

    modelfile = ollama_dir / "Modelfile"
    modelfile.write_text(
        "\n".join(
            [
                "# Generated by paroquant export",
                f"FROM {rel_path.as_posix()}",
            ]
        )
        + "\n"
    )
    return modelfile


def build_lmstudio(
    lmstudio_dir: Path,
    model_id: str,
    mlx_dir: Path | None,
    gguf_outputs: dict[str, Path] | None,
) -> Path:
    """Write a publish-ready model.yaml with MLX primary + GGUF fallback artifacts."""
    lmstudio_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "id: paroquant-export",
        f"name: {model_id.replace('/', '-')}",
        "description: Generated ParoQuant compatibility export",
        "license: apache-2.0",
        "artifacts:",
    ]

    if mlx_dir is not None and mlx_dir.exists():
        lines.extend(
            [
                "  - type: mlx",
                "    preferred: true",
                "    path: ../mlx",
            ]
        )

    if gguf_outputs:
        for quant, path in gguf_outputs.items():
            if quant == "f16":
                continue
            lines.extend(
                [
                    "  - type: gguf",
                    f"    quantization: {quant}",
                    f"    path: ../gguf/{path.name}",
                ]
            )

    model_yaml = lmstudio_dir / "model.yaml"
    model_yaml.write_text("\n".join(lines) + "\n")
    return model_yaml


def write_manifest(output_dir: Path, payload: dict[str, Any]) -> Path:
    """Write export manifest with deterministic artifact hashes."""
    artifacts = payload.get("artifacts", {})
    artifact_hashes: dict[str, dict[str, str]] = {}

    for name, value in artifacts.items():
        if isinstance(value, str):
            p = Path(value)
            if p.exists():
                artifact_hashes[name] = _hash_tree(p)
        elif isinstance(value, list):
            bundle: dict[str, str] = {}
            for item in value:
                p = Path(item)
                if p.exists() and p.is_file():
                    bundle[p.name] = _sha256_file(p)
            artifact_hashes[name] = bundle
        elif isinstance(value, dict):
            bundle: dict[str, str] = {}
            for k, v in value.items():
                p = Path(v)
                if p.exists() and p.is_file():
                    bundle[k] = _sha256_file(p)
            artifact_hashes[name] = bundle

    payload = dict(payload)
    payload["hashes"] = artifact_hashes

    manifest = output_dir / "manifest.json"
    manifest.write_text(json.dumps(payload, indent=2) + "\n")
    return manifest
